name: Go CI

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: minerva_user
          POSTGRES_PASSWORD: secure_password
          POSTGRES_DB: minerva_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.23.4'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go modules
        run: go mod download

      - name: Clean Go module cache
        run: go clean -modcache

      - name: Copy config file
        run: cp ./minerva_config.example.toml ./cmd/minerva/minerva_config.toml

      - name: Verify Go modules checksums
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -U minerva_user -d minerva_test -h 127.0.0.1; do sleep 1; done

      - name: Create database schema
        run: |
          export PGPASSWORD=secure_password
          psql -h 127.0.0.1 -U minerva_user -d minerva_test -f docs/data_schema.sql

      - name: Test
        run: go test -v ./... -coverprofile=coverage.out ./...