name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: minerva_user  # Match your test constants
          POSTGRES_PASSWORD: secure_password # Match your test constants
          POSTGRES_DB: minerva_test # Match your test constants
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.23.4' # Or your preferred Go version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go modules
        run: go mod download

      - name: Copy config file # Make config file available
        run: cp ./minerva_config.example.toml ./cmd/minerva/minerva_config.toml

      - name: Verify Go modules checksums
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -coverprofile=coverage.out ./...
